# Generated by Django 2.0 on 2020-06-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=6)),
                ('dish_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('delievery_status', models.BooleanField(default=False)),
                ('cost', models.FloatField()),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
