# Generated by Django 2.0 on 2020-06-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_order',
            field=models.BooleanField(default=False),
        ),
    ]
