# Generated by Django 2.0 on 2020-06-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0004_order_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=25)),
                ('price', models.FloatField(default=0.0)),
                ('category', models.CharField(max_length=10)),
            ],
        ),
    ]
