# Generated by Django 2.0 on 2020-06-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0005_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
