# Generated by Django 2.0 on 2020-06-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0008_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='percentage',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
