# Generated by Django 2.0 on 2020-06-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0009_offers_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='cost_applicable',
            field=models.FloatField(default=100.0),
        ),
    ]
